# filegroup(
#   name       = "asic_world_v_files",
#   srcs       = glob(["asic_world/*.v"]),
#   visibility = ["//visibility:public"],
# )
#
# filegroup(
#   name         = "misc",
#   srcs         = glob(["misc/*.v"]),
#   visibility   = ["//visibility:public"],
# )

exports_files(
  [glob(["misc/*.v"])],
  visibility = ["//visibility:public"],
)
